FROM python:3.12-slim
WORKDIR /app
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1
COPY pyproject.toml /app/
RUN pip install --no-cache-dir ".[test]"
RUN apt-get update && apt-get install -y --no-install-recommends libgomp1 && rm -rf /var/lib/apt/lists/*
COPY . /app
RUN python -m ipykernel install --user --name python3
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
